services:
  daed:
    image: ghcr.io/daeuniverse/daed
    container_name: daed
    privileged: true
    network_mode: host
    pid: host
    mem_limit: 1g
    memswap_limit: 1g
    mem_reservation: 512m
    restart: always
    volumes:
      - /sys:/sys
      - /etc/daed:/etc/daed
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai        
