services:
  easytier:
    image: easytier/easytier:latest
    container_name: easytier

    restart: always
    network_mode: host
    privileged: true

    environment:
      - TZ=Asia/Shanghai

    working_dir: /root
    volumes:
      -./conf/cache:/root

    entrypoint:
      - /sbin/tini
      - --
      - /bin/sh
      - -c
      - |
        easytier-core \
          --config-server udp://127.0.0.1:22020/admin &

        easytier-web-embed --api-host http://127.0.0.1:11211
