services:
  easytier:
    image: easytier/easytier:unstable
    hostname: easytier
    container_name: easytier
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./easytier:/root
      - ./machine-id:/etc/machine-id:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        easytier-core --config-server udp://0.0.0.0:22020/admin & \
        easytier-web-embed \
          --api-server-port 11211 \
          --api-host http://127.0.0.1:11211 \
          --config-server-port 22020 \
          --config-server-protocol udp
