services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 58090:8090
    environment:
      - XIAOMUSIC_PUBLIC_PORT=58090
    volumes:
      - /xiaomusic_music:/app/music
      - /root/docker/xiaomusic_conf:/app/conf
