services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 必须挂载，以便监控
    environment:
      - TZ=Asia/Shanghai # 设置时区，方便日志查看
      # 如果需要通过环境变量排除容器，可以在这里设置 WATCHTOWER_SCOPE 或 WATCHTOWER_IGNORE
    
    # 🔑 核心功能通过 command 传入，优先级最高
    # 建议实际使用时，将 --interval 120 修改为 --interval 86400 (24小时)
    command: --interval 86400 --cleanup --rolling-restart   # jellyfin
