services:
  iptv:
    image: ardovini/viniplay:latest
    container_name: iptv
    ports:
      - "8998:8998"
    restart: always
    volumes:
      - ./viniplay-data:/data
    env_file:
      - ./.env
