services:
  iptv:
    image: 'guovern/iptv-api'
    container_name: iptv
    volumes:
      - '/etc/docker/iptv/config:/iptv-api/config'
      - '/etc/docker/iptv/output:/iptv-api/output'
    ports:
      - '8000:8000'
    restart: always
